# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target ‘JYMultiLevel’ do

   pod 'ReactiveSwift', '1.0.0-alpha.3'

end


